# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    versioning:
        enabled: false
    allowed_methods_listener:  false
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
            - { path: '^/api', priorities: [json], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: false }
    view:
        view_response_listener:  true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/, prefer_extension: true, priorities: [ html ] }
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
